# Generated by Django 3.2.12 on 2023-05-19 13:12

from django.db import migrations

def load_initial_data(apps, schema_editor):
    # get our model
    # get_model(appname, modelname)
    estado_model = apps.get_model('geps', 'Estado')
    for i in ['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT',
	  'MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO',
	  'RR','SC','SP','SE','TO']:
        estado_model.objects.create(sigla = i)

def clean_reverse_data(apps, schema_editor):
    estado_model = apps.get_model('geps', 'Estado')
    estado_model.objects.all().delete()
        

class Migration(migrations.Migration):

    dependencies = [
        ('geps', '0008_cria_grupos'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, clean_reverse_data),
    ]
